---
kind: pkgfile.Build
spec:
  targets:
    - sbc-jetson
  extraBuildArgs:
    - PKGS_PREFIX
    - PKGS
  makefile:
    extraVariables:
      - name: PKGS_PREFIX
        defaultValue: ghcr.io/siderolabs
      - name: PKGS
        defaultValue: v1.8.0-alpha.0-46-g124d35b
---
kind: common.Build
spec:
    ignoredPaths:
      - go.work.sum
